# Generated by Django 5.2.4 on 2025-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('American', 'American'), ('British', 'British'), ('Brazilian', 'Brazilian'), ('Canadian', 'Canadian'), ('Australian', 'Australian'), ('Other', 'Other')], max_length=50, null=True)),
            ],
        ),
    ]
